universe = vanilla
executable = 1run.sh
arguments = $(ProcId)
output = /fcc/tikim/results/ele/air/e_20GeV_0th//log/$(ProcId).out
error = /fcc/tikim/results/ele/air/e_20GeV_0th//log/$(ProcId).err
log = /fcc/tikim/results/ele/air/e_20GeV_0th//log/$(ProcId).log
request_memory = 3 GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files =./bin, ./lib, ./init.mac, ./1run.mac
queue 500
